const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const themes = {
	dark: {
		'primary-color': '#1DA57A',
	},
	default: {

	}
};

module.exports = function({theme}) {
	return {
		entry: [
			'./src/index.js',
		],
		plugins: [
			new HtmlWebpackPlugin({
				inject: true, // Inject all files that are generated by webpack, e.gx. bundle.js
				template: './src/index.html',
			}),
			new MiniCssExtractPlugin({
				filename: `./css/${theme}.css`
			})
		],
		output: {
			path: path.resolve(__dirname, 'dist'),
			filename: 'bundle.js',
		},
		module: {
			rules: [
				{
					test: /\.html$/,
					use: 'html-loader',
				},
				{
					test: /\.?js$/,
					exclude: /(node_modules|bower_components)/,

					use: {
						loader: 'babel-loader',
					},
				},
				{
					test: /\.less$/,
					use: [
						MiniCssExtractPlugin.loader,
						{
							loader: 'css-loader',
						},
						{
							loader: 'less-loader',
							options: {
								strictMath: false,
								noIeCompat: true,
								javascriptEnabled: true,
								modifyVars: themes[theme],
							},
						},
					],
				},
			],
		},
	}
};
